archetypeDir = 'archetypes'
assetDir = 'assets'
baseURL = 'https://mpetteno.github.io/portfolio/'
buildDrafts = false
buildExpired = false
buildFuture = false
canonifyURLs = false
capitalizeListTitles = true
cleanDestinationDir = false
contentDir = 'content'
copyright = ''
dataDir = 'data'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
disableAliases = false
disableHugoGeneratorInject = false
# disableKinds = ''
# disableLanguages = ''
disableLiveReload = false
disablePathToLower = false
enableEmoji = false
enableGitInfo = false
enableMissingTranslationPlaceholders = false
enableRobotsTXT = false
environment = false
hasCJKLanguage = false
ignoreCache = false
ignoreLogs = ''
ignoreVendorPaths = ''
languageCode = 'en'
layoutDir = 'layouts'
newContentEditor = ''
noBuildLock = false
noChmod = false
noTimes = false
panicOnWarning = false
pluralizeListTitles = true
printI18nWarnings = false
printPathWarnings = false
printUnusedTemplates = false
publishDir = 'public'
refLinksErrorLevel = 'ERROR'
refLinksNotFoundURL = ''
relativeURLs = false
removePathAccents = false
# renderSegments = ''
# sectionPagesMenu = 'main'
summaryLength = 0
templateMetrics = false
templateMetricsHints = false
theme = "vapor"
themesDir = "themes"
timeout = '30s'
timeZone = ''
title = 'Portfolio'
titleCaseStyle = 'ap'
uglyURLs = false
watch = false
