defaultMarkdownHandler = 'goldmark'

[goldmark]
    duplicateResourceFiles = false
    [goldmark.extensions]
        definitionList = true
        footnote = true
        linkify = true
        linkifyProtocol = 'https'
        strikethrough = true
        table = true
        taskList = true
        typographer = true
        [goldmark.extensions.cjk]
            eastAsianLineBreaks = false
            eastAsianLineBreaksStyle = 'simple'
            enable = false
            escapedSpace = false
        [goldmark.extensions.extras]
            [goldmark.extensions.extras.delete]
                enable = false
            [goldmark.extensions.extras.insert]
                enable = false
            [goldmark.extensions.extras.mark]
                enable = false
            [goldmark.extensions.extras.subscript]
                enable = false
            [goldmark.extensions.extras.superscript]
                enable = false
        [goldmark.extensions.passthrough]
            enable = false
            [goldmark.extensions.passthrough.delimiters]
                block = []
                inline = []
    [goldmark.parser]
        autoHeadingID = true
        autoHeadingIDType = 'github'
        wrapStandAloneImageWithinParagraph = true
        [goldmark.parser.attribute]
            block = false
            title = true
    [goldmark.renderHooks]
        [goldmark.renderHooks.image]
            useEmbedded = "fallback"
        [goldmark.renderHooks.link]
            useEmbedded = "fallback"
    [goldmark.renderer]
        hardWraps = false
        unsafe = true
        xhtml = true
