
author = "Matteo Petten√≤"
singlePage = true
defaultThemeMode = 'light'
languageSelector = false
themeModeSwitcher = true
searchBar = false
googleFontName = "Open+Sans:ital,wght@0,300..800;1,300..800"
formspreeFormUrl = 'https://formspree.io/f/xqakprqn'
fontawesomeKitUrl = 'https://kit.fontawesome.com/3fe49439a1.js'

[[social]]
    identifier = 'github-personal'
    name = 'Github'
    url = 'https://github.com/mpetteno'
    icon = 'fa-brands fa-github'
    title = 'github-personal'
    weight = 10
    rel = 'external'
    target = '_blank'
    hide = false
[[social]]
    identifier = 'github-polimi'
    name = 'Github Polimi'
    url = 'https://github.com/mpetteno-polimi'
    icon = 'fa-brands fa-github'
    title = 'github-polimi'
    weight = 20
    rel = 'external'
    target = '_blank'
    hide = true
[[social]]
    identifier = 'linkedin'
    name = 'Linkedin'
    url = 'https://www.linkedin.com/in/mpetteno/'
    icon = 'fa-brands fa-linkedin'
    title = 'linkedin'
    weight = 30
    rel = 'external'
    target = '_blank'
    hide = false
[[social]]
    identifier = 'email'
    name = 'Email'
    url = '#contactme'
    icon = 'fa-solid fa-envelope'
    title = 'email'
    weight = 120
    rel = 'next'
    target = '_self'
    hide = true
[[social]]
    identifier = 'kaggle'
    name = 'Kaggle'
    url = 'https://www.kaggle.com/dock56'
    icon = 'fa-brands fa-kaggle'
    title = 'kaggle'
    weight = 50
    rel = 'external'
    target = '_blank'
    hide = true
[[social]]
    identifier = 'goodreads'
    name = 'Goodreads'
    url = 'https://www.goodreads.com/mpetteno'
    icon = 'fa-brands fa-goodreads'
    title = 'goodreads'
    weight = 140
    rel = 'external'
    target = '_blank'
    hide = false
[[social]]
    identifier = 'untappd'
    name = 'Untappd'
    url = 'https://untappd.com/user/doc_56'
    icon = 'fa-brands fa-untappd'
    title = 'untappd'
    weight = 80
    rel = 'external'
    target = '_blank'
    hide = true
[[social]]
    identifier = 'strava'
    name = 'Strava'
    url = 'https://www.strava.com/athletes/doc56'
    icon = 'fa-brands fa-strava'
    title = 'strava'
    weight = 130
    rel = 'external'
    target = '_blank'
    hide = false
[[social]]
    identifier = 'pinterest'
    name = 'Pinterest'
    url = 'https://it.pinterest.com/doc_36/'
    icon = 'fa-brands fa-pinterest'
    title = 'pinterest'
    weight = 80
    rel = 'external'
    target = '_blank'
    hide = true
[[social]]
    identifier = 'reddit'
    name = 'Reddit'
    url = 'https://www.reddit.com/user/doc_56/'
    icon = 'fa-brands fa-reddit'
    title = 'reddit'
    weight = 90
    rel = 'external'
    target = '_blank'
    hide = true
[[social]]
    identifier = 'research-gate'
    name = 'ResearchGate'
    url = 'https://www.researchgate.net/profile/Matteo-Petteno-3'
    icon = 'fa-brands fa-researchgate'
    title = 'research-gate'
    weight = 110
    rel = 'external'
    target = '_blank'
    hide = false
[[social]]
    identifier = 'google-scholar'
    name = 'Google Scholar'
    url = 'https://scholar.google.com/citations?user=lgPPQUUAAAAJ'
    icon = 'fa-brands fa-google-scholar'
    title = 'google-scholar'
    weight = 100
    rel = 'external'
    target = '_blank'
    hide = false